models.py
from extensions import db
import flask_login

class Markets(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(20))
    symbol = db.Column(db.String(20))
    trend = db.Column(db.String(20))

class MarketsPro(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(20))
    symbol = db.Column(db.String(20))
    trend = db.Column(db.String(20))

class User(flask_login.UserMixin):
    pass

routes.py
from flask import Flask,render_template, request, url_for, redirect, flash
import flask_login
from flask import Blueprint
from extensions import db, login_manager
from models import User, Markets, MarketsPro
from utilities import data, markets, markets_data, marketspro_data, get_trend, send_mail
import threading


main = Blueprint('main', __name__)



@main.route('/')
def index_get():
    all_markets = Markets.query.order_by(Markets.name).all()
    return render_template('index.html',all_markets=all_markets,  data=markets_data )

@main.route('/pro')
@flask_login.login_required
def pro_get():
    all_markets = MarketsPro.query.order_by(MarketsPro.name).all()
    return render_template('pro.html',all_markets=all_markets,  data=marketspro_data)

@main.route('/', methods=['POST'])
def index_post():
    err_msg = ''
    new_market = request.form.get('market')
    markets = {
    'S&P 500' : 'SP500',
    'GOLD' : 'GOLDAMGBD228NLBM',
    'BITCOIN' : 'CBBTCUSD'
    }   
    if new_market:
        existing_market = Markets.query.filter_by(name=new_market).first()
        if not existing_market:
            symbol = markets[new_market]
            new_trend = get_trend(symbol)
            data = Markets(name=new_market, symbol=symbol, trend=new_trend)
            db.session.add(data)
            db.session.commit()
        else:
            err_msg = 'MARKET ALREADY ADDED. BECOME A PRO MEMBER AND GET ACCESS TO MORE FINANCIAL INSTRUMENTS!'

    if err_msg:
        flash(err_msg)
    else:
        flash('MARKET ADDED. BECOME A PRO MEMBER AND GET ACCESS TO MORE FINANCIAL INSTRUMENTS!')
    return redirect(url_for('main.index_get'))

@main.route('/pro', methods=['POST'])
@flask_login.login_required
def pro_post():
    err_msg = ''
    new_market = request.form.get('market') 
    if new_market:
        existing_market = MarketsPro.query.filter_by(name=new_market).first()
        if not existing_market:
            symbol = markets[new_market]
            new_trend = get_trend(symbol)
            data = MarketsPro(name=new_market, symbol=symbol, trend=new_trend)
            db.session.add(data)
            db.session.commit()
        else:
            err_msg = 'MARKET ALREADY ADDED'

    if err_msg:
        flash(err_msg)
    else:
        flash('MARKET ADDED')
    return redirect(url_for('main.pro_get'))



@main.route('/delete/<int:id>')
def delete(id):
    market = Markets.query.get_or_404(id)
    db.session.delete(market)
    db.session.commit()
    return redirect(url_for('main.index_get'))

@main.route('/delete_pro/<int:id>')
@flask_login.login_required
def delete_pro(id):
    market = MarketsPro.query.get_or_404(id)
    db.session.delete(market)
    db.session.commit()
    return redirect(url_for('main.pro_get'))

@main.route('/update/<int:id>')
def update(id):
    market = Markets.query.get_or_404(id)
    symbol = market.symbol
    new_trend = get_trend(symbol)
    market.trend = new_trend
    db.session.commit()
    return redirect(url_for('main.index_get'))

@main.route('/update_pro/<int:id>')
@flask_login.login_required
def update_pro(id):
    market = MarketsPro.query.get_or_404(id)
    symbol = market.symbol
    new_trend = get_trend(symbol)
    market.trend = new_trend
    db.session.commit()
    return redirect(url_for('main.pro_get'))

@main.route('/login', methods=['GET', 'POST'])
def login():
    if request.method == 'GET':
        return render_template('login.html')

    try:
        name = request.form['name']
        if request.form['password'] == data[name]['password']:
            user = User()
            user.id = name
            flask_login.login_user(user)
            return redirect(url_for('main.pro_get'))
        flash('WRONG NAME OR PASSWORD!')
        return redirect(url_for('main.login'))
    except KeyError:
        flash('WRONG NAME OR PASSWORD!')
        return redirect(url_for('main.login'))



@main.route('/logout')
@flask_login.login_required
def logout():
    flask_login.logout_user()
    return render_template('logout.html')

@main.route('/register', methods=['GET', 'POST'])
def register():
    if request.method == "POST":
        name = request.form['name']
        email = request.form['email']
        t1 = threading.Thread(target=send_mail, args=[name, email])
        t1.start()
        flash('THANK YOU. PLEASE CHECK YOUR EMAIL!')
        return redirect(url_for('main.login'))
    return render_template('register.html')


@login_manager.unauthorized_handler
def unauthorized_handler():
    return render_template('unauthorized.html')

@main.app_errorhandler(404)
def not_found(e):
    return render_template('404.html'), 404

@main.app_errorhandler(500)
def internal_server_error(e):
    return render_template('500.html'), 500

templates/index.html
{% extends 'base.html' %} {% block title %} Home {% endblock %}{% block content %}<table class="select"><tr><td><form class="form-inline" method="POST" action="{{ url_for('main.index_post') }}"><div><div class="input-group"> <span class="input-group-addon">SELECT YOUR MARKET:</span> <select name="market" id='selection' class="selectpicker form-control"> {% for o in data %}<option value="{{ o.name }}" id="option">{{ o.name }}</option> {% endfor %} </select></div> <button type="submit" class="button-left" id="btn-sel">SEND</button></div></form></td></tr></table>{% with messages = get_flashed_messages() %} {% if messages %} {% for message in messages %}<div class="msg_display"><p> {{ message }}</p><form action="{{ url_for('main.index_get') }}"> <button id="btn-msg"><i class="fas fa-times-circle"></i></button></form></div> {% endfor %} {% endif %} {% endwith %}<div class="table"><table><tr><td>MARKET</td><td>TREND</td><td>ACTION</td></tr></table> {% for market in all_markets %}<table><tr><td>{{ market.name }}</td> {% if market.trend == 'BULLISH' %}<td><i class="fas fa-arrow-circle-up"></i> {{ market.trend }}</td> {% else %}<td><i class="fas fa-arrow-circle-down"></i> {{ market.trend }}</td> {% endif %}<td class="buttons"><button class="button-left"><a href='/update/{{market.id}}'>UPDATE</a></button><button class="button-right"><a href='/delete/{{market.id}}'>DELETE</a></button></td></tr></table> {% endfor %}</div> {% endblock content %}

templates/login.html
{% extends 'base.html' %} {% block title %} Login {% endblock %}{% block content %}<div class="login_display"><form action="{{ url_for('main.login') }}", method='POST'><div class="form__control"> <input type="text" name="name" placeholder="PLEASE ENTER NAME" required></div><div class="form__control"> <input type="text" name="password" placeholder="PLEASE ENTER PASSWORD" required></div><div class="form__control"> <input type="submit" value="LOGIN" class="button-left" id="btn-sel"></div></form></div> {% with messages = get_flashed_messages() %} {% if messages %} {% for message in messages %}<div class="msg_logout"><p> {{ message }}</p><form action="{{ url_for('main.login') }}"> <button id="btn-msg"><i class="fas fa-times-circle"></i></button></form></div> {% endfor %} {% endif %} {% endwith %} {% endblock content %}

templates/logout.html
{% extends 'base.html' %} {% block title %} Logout {% endblock %}{% block content %}<div class="msg_display"><h4>YOU HAVE BEEN LOGGED OUT!</h4><form action="{{ url_for('main.index_get') }}"> <button id="btn-msg"><i class="fas fa-times-circle"></i></button></form></div>{% endblock content %}

templates/pro.html
{% extends 'base.html' %} {% block title %} Pro {% endblock %}{% block content %}<table class="select"><tr><td><form class="form-inline" method="POST" action="{{ url_for('main.pro_post') }}"><div><div class="input-group"> <span class="input-group-addon">SELECT YOUR MARKET:</span> <select name="market" id='selection' class="selectpicker form-control"> {% for o in data %}<option value="{{ o.name }}" id="option">{{ o.name }}</option> {% endfor %} </select></div> <button type="submit" class="button-left" id="btn-sel">SEND</button></div></form></td></tr></table>{% with messages = get_flashed_messages() %} {% if messages %} {% for message in messages %}<div class="msg_display"><p> {{ message }}</p><form action="{{ url_for('main.pro_get') }}"> <button id="btn-msg"><i class="fas fa-times-circle"></i></button></form></div> {% endfor %} {% endif %} {% endwith %}<div class="table"><table><tr><td>MARKET</td><td>TREND</td><td>ACTION</td></tr></table> {% for market in all_markets %}<table><tr><td>{{ market.name }}</td> {% if market.trend == 'BULLISH' %}<td><i class="fas fa-arrow-circle-up"></i> {{ market.trend }}</td> {% else %}<td><i class="fas fa-arrow-circle-down"></i> {{ market.trend }}</td> {% endif %}<td class="buttons"><button class="button-left"><a href='/update_pro/{{market.id}}'>UPDATE</a></button><button class="button-right"><a href='/delete_pro/{{market.id}}'>DELETE</a></button></td></tr></table> {% endfor %}</div> {% endblock content %}

templates/register.html
{% extends 'base.html' %} {% block title %} Register {% endblock %}{% block content %}<div class="login_display"><form action="{{ url_for('main.register') }}", method='POST'><div class="form__control"> <input type="text" name="name" placeholder="PLEASE ENTER NAME" required></div><div class="form__control"> <input type="email" name="email" placeholder="PLEASE ENTER EMAIL" required></div><div class="form__control"> <input type="submit" value="REGISTER" class="button-left" id="btn-sel"></div></form></div> {% endblock content %}

templates/unauthorized.html
{% extends 'base.html' %} {% block title %} Unauthorized {% endblock %}{% block content %}<div class="msg_display"><h4>PLEASE GO TO <a href="{{ url_for('main.login') }}">LOGIN</a> FIRST!</h4><form action="{{ url_for('main.index_get') }}"> <button id="btn-msg"><i class="fas fa-times-circle"></i></button></form></div>{% endblock content %}